apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
  labels:
    deployment: celery-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: celery-worker
  template:
    metadata:
      labels:
        pod: celery-worker
    spec:
      containers:
        - name: celery-worker
          image: gethue/hue
          command: ['./build/env/bin/celery', 'worker', '-A', 'desktop', '-l', 'info']
          volumeMounts:
          - name: config-volume
            mountPath: /usr/share/hue/desktop/conf/z-hue.ini
            subPath: hue-ini
      volumes:
        - name: config-volume
          configMap:
            name: hue-config
