apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: celery-flower
  labels:
    deployment: celery-flower
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: celery-flower
  template:
    metadata:
      labels:
        pod: celery-flower
    spec:
      containers:
      - name: celery-flower
        image: gethue/hue
        command: ['./build/env/bin/celery', 'flower', '-A', 'desktop']
        ports:
          - containerPort: 5555
        resources:
          limits:
            cpu: 100m
        volumeMounts:
        - name: config-volume
          mountPath: /usr/share/hue/desktop/conf/z-hue.ini
          subPath: hue-ini
      volumes:
        - name: config-volume
          configMap:
            name: hue-config
