# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-20 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beeswax', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='guid',
            field=models.TextField(max_length='100'),
        ),
        migrations.AlterField(
            model_name='session',
            name='secret',
            field=models.TextField(max_length='100'),
        ),
    ]
