# Generated by Django 3.2.25 on 2025-01-09 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beeswax', '0003_compute_namespace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compute',
            name='is_ready',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
