/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package org.apache.hadoop.thriftfs.api;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;
public enum DatanodeState implements TEnum{
    NORMAL_STATE(1),
    DECOMMISSION_INPROGRESS(2),
    DECOMMISSIONED(3);

  private static final Map<Integer, DatanodeState> BY_VALUE = new HashMap<Integer,DatanodeState>() {{
    for(DatanodeState val : DatanodeState.values()) {
      put(val.getValue(), val);
    }
  }};

  private final int value;

  private DatanodeState(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static DatanodeState findByValue(int value) { 
    return BY_VALUE.get(value);
  }
}
