'\" t
.\"     Title: odf2zwikimoin
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 01/09/2013
.\"    Manual: [FIXME: manual]
.\"    Source: [FIXME: source]
.\"  Language: English
.\"
.TH "ODF2ZWIKIMOIN" "1" "01/09/2013" "[FIXME: source]" "[FIXME: manual]"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
odf2zwikimoin \- Convert ODF to ZWiki MoinMoin format
.SH "SYNOPSIS"
.HP \w'\fBodf2zwikimoin\fR\ 'u
\fBodf2zwikimoin\fR \fIpath\fR
.SH "DESCRIPTION"
.PP
\fBodf2zwikimoin\fR
is a program that will create a ZWiki MoinMoin format\&. See http://zwiki\&.org/\&.
.PP
"Path" is assumed to be an OpenDocument file of text, spreadsheet or presentation type\&.
.SH "EXAMPLE"
.sp
.if n \{\
.RS 4
.\}
.nf
odf2zwikimoin odf\-file
.fi
.if n \{\
.RE
.\}
