# Welcome to Hue (http://gethue.com) Dockerfile
# Build an image from a remote github or local cloned Hue repository.

FROM gethue/hue:latest
LABEL description="Hue Image for CI"

LABEL com.circleci.preserve-entrypoint=true

ENTRYPOINT contacts
