# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-01-12 14:53
from __future__ import unicode_literals

import desktop.models
from django.db import migrations, models
import django_prometheus.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(db_index=True, help_text='App that this configuration belongs to.', max_length=32)),
                ('properties', models.TextField(default='[]', help_text='JSON-formatted default properties values.')),
                ('is_default', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'ordering': ['app', '-is_default', 'user'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('description', models.TextField(default='')),
                ('last_modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Last modified')),
                ('version', models.SmallIntegerField(default=1, verbose_name='Schema version')),
                ('extra', models.TextField(default='')),
                ('object_id', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Document2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('description', models.TextField(default='')),
                ('uuid', models.CharField(db_index=True, default=desktop.models.uuid_default, max_length=36)),
                ('type', models.CharField(db_index=True, default='', help_text='Type of document, e.g. Hive query, Oozie workflow, Search Dashboard...', max_length=32)),
                ('data', models.TextField(default='{}')),
                ('extra', models.TextField(default='')),
                ('search', models.TextField(blank=True, help_text='Searchable text for the document.', null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Time last modified')),
                ('version', models.SmallIntegerField(db_index=True, default=1, verbose_name='Document version')),
                ('is_history', models.BooleanField(db_index=True, default=False)),
                ('is_managed', models.BooleanField(db_index=True, default=False, verbose_name='If managed under the cover by Hue and never by the user')),
                ('is_trashed', models.NullBooleanField(db_index=True, default=False, verbose_name='True if trashed')),
            ],
            options={
                'ordering': ['-last_modified', 'name'],
            },
            bases=(models.Model, django_prometheus.models.ExportModelOperationsMixin('Document2')),
            #bases=(models.Model, django_prometheus.models.Mixin),
        ),
        migrations.CreateModel(
            name='Document2Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perms', models.CharField(choices=[('read', 'read'), ('write', 'write'), ('comment', 'comment'), ('link_read', 'link read'), ('link_write', 'link write')], db_index=True, default='read', max_length=10)),
                ('is_link_on', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perms', models.CharField(choices=[('read', 'read'), ('write', 'write')], default='read', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collect_usage', models.BooleanField(db_index=True, default=True)),
                ('tours_and_tutorials', models.BooleanField(db_index=True, default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20)),
                ('value', models.TextField(max_length=4096)),
            ],
        ),
    ]
