#!/bin/bash

cd `dirname $0`

	#-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5006 \

exec java \
	-cp "java/sparker-repl/target/lib/*:java/sparker-repl/target/sparker-repl-3.7.0-SNAPSHOT.jar" \
	com.cloudera.hue.sparker.repl.Main -usejavacp "$@" 2>/dev/null
