{{- if .Values.website.jp.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-jp
  labels:
    deployment: website-jp
spec:
  selector:
    matchLabels:
      pod: website-jp
  replicas: 1
  template:
    metadata:
      labels:
        pod: website-jp
    spec:
      containers:
      - name: website-jp
        image: {{ .Values.image.registry }}/website-jp:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 80
        resources:
          requests:
            # memory: "100Mi"
            cpu: "10m"
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 60
          failureThreshold: 30
{{- end -}}
