{{- if .Values.docs.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docs
  labels:
    deployment: docs
spec:
  selector:
    matchLabels:
      pod: docs
  replicas: 1
  template:
    metadata:
      labels:
        pod: docs
    spec:
      containers:
      - name: docs
        image: {{ .Values.image.registry }}/documentation:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - containerPort: 80
        resources:
          requests:
            # memory: "100Mi"
            cpu: "10m"
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 60
          failureThreshold: 30
{{- end -}}
