{{- if and .Values.ingress.create (eq .Values.ingress.type "nginx-ssl") -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: gethue-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-website-prod
    certmanager.k8s.io/acme-challenge-type: http01
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "hue-website-ingress"
    nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
spec:
  rules:
  {{ if .Values.docs.enabled }}
  - host: {{ .Values.docs.domain }}
    http:
      paths:
      - backend:
          serviceName: docs
          servicePort: 80
        path: /
  {{ end }}
  {{ if .Values.website.enabled }}
  - host: {{ .Values.website.domain }}
    http:
      paths:
      - backend:
          serviceName: website
          servicePort: 80
        path: /
  {{ end }}
  tls:
  - hosts:
    {{- if .Values.docs.enabled -}}
    - {{ .Values.docs.domain }}
    {{- end -}}
    {{- if .Values.website.enabled -}}
    - {{ .Values.website.domain }}
    {{- end -}}
    secretName: letsencrypt-website-prod
{{- end -}}
