{{- if and .Values.ingress.create (eq .Values.ingress.type "nginx-ssl") -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: gethue
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-website-prod
    cert-manager.io/acme-challenge-type: http01
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "gethue-website"
    nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
    {{ if .Values.ingress.hasAuth }}
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: basic-auth-gethue
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
    {{ end }}
spec:
  rules:
  {{ if .Values.docs.enabled }}
  - host: {{ .Values.docs.domain }}
    http:
      paths:
      - backend:
          serviceName: docs
          servicePort: 9001
        path: /
  {{ end }}
  {{ if .Values.website.enabled }}
  - host: {{ .Values.website.domain }}
    http:
      paths:
      - backend:
          serviceName: website
          servicePort: 9002
        path: /
  {{ end }}
  {{ if .Values.website.jp.enabled }}
  - host: {{ .Values.website.jp.domain }}
    http:
      paths:
      - backend:
          serviceName: website-jp
          servicePort: 9002
        path: /
  {{ end }}
  tls:
  - hosts:
    {{ if .Values.docs.enabled }}
    - {{ .Values.docs.domain }}
    {{ end }}
    {{ if .Values.website.enabled }}
    - {{ .Values.website.domain }}
    {{ end }}
    {{ if .Values.website.jp.enabled }}
    - {{ .Values.website.jp.domain }}
    {{ end }}
    secretName: letsencrypt-website-prod-tls
{{- end -}}
