{{- if .Values.website.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: website
  labels:
    pod: website
spec:
  selector:
    pod: website
  ports:
  - name: website
    port: 9002
    targetPort: 80
  type: NodePort
{{- end -}}
