{{- if .Values.website.jp.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: website-jp
  labels:
    pod: website-jp
spec:
  selector:
    pod: website-jp
  ports:
  - name: website-jp
    port: 9002
    targetPort: 80
  type: NodePort
{{- end -}}
