copyright: Apache License v2.0
description: Shared components for Hue
name: ccs-shared
sources: [
  Source/Fx/Fx.Shake.js,
  Source/JFrameFilters/CCS.JFrame.Deprecated.js,
  Source/CCS/CCS.js,
  Source/CCS/CCS.Desktop.js,
  Source/CCS/CCS.Desktop.FlashMessage.js,
  Source/CCS/CCS.Desktop.Config.js,
  Source/CCS/CCS.Desktop.BackgroundManager.js,
  Source/CCS/CCS.Dock.js,
  Source/CCS/CCS.JBrowser.js,
  Source/CCS/CCS.JFrame.js,
  Source/CCS/CCS.Login.js,
  Source/CCS/CCS.Request.js,
  Source/CCS/CCS.SolidWindow.js,
  Source/CCS/CCS.User.js,
  Source/CCS/HueChart.js,
  Source/CCS/HueChart.Box.js,
  Source/CCS/HueChart.Area.js,
  Source/CCS/HueChart.Line.js,
  Source/CCS/HueChart.Circle.js,
  Source/CCS/HueChart.GroupValueManager.js,
  Source/UI/StickyWin.UI.Solid.js,
  Source/UI/ThumbTack.js,
  Source/JFrameLinkers/CCS.JFrame.Chooser.js,
  Source/Native/String.CCS.js,
  Source/Native/Number.Files.js,
  Source/StaticThirdParty/DynamicTextarea.js,

]
version: Unknown
