#!/bin/bash
# Licensed to Cloudera, Inc. under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  Cloudera, Inc. licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# Common functions for hudson build scripts

#
# Use $CDH_URL to control where to download Hadoop.
# If not specified, it uses the $CDH variable to select an archive location.
#

CDH_URL=${CDH_URL:-http://archive.cloudera.com/cdh/3/hadoop-0.20.2-CDH3B4.tar.gz}

CDH_TGZ=$(basename $CDH_URL)
CDH_VERSION=${CDH_TGZ/.tar.gz/}
CDH_CACHE="$HOME/.hue_cache/${CDH_TGZ}"

build_hadoop() {
  if [ ! -f $CDH_CACHE ]; then
    mkdir -p $HOME/.hue_cache
    echo "Downloading $CDH_URL..."
    wget $CDH_URL -O $CDH_CACHE
  fi

  HADOOP_DIR=$HUE_ROOT/ext/hadoop

  mkdir -p $HADOOP_DIR
  echo "Unpacking $CDH_CACHE to $HADOOP_DIR"
  tar -C $HADOOP_DIR -xzf $CDH_CACHE
  export HADOOP_HOME="$HADOOP_DIR/${CDH_VERSION}"
}

HIVE_URL=${HIVE_URL:-http://archive.cloudera.com/cdh/3/hive-0.7.0-CDH3B4.tar.gz}

HIVE_TGZ=$(basename $HIVE_URL)
HIVE_VERSION=${HIVE_TGZ/.tar.gz/}
HIVE_CACHE="$HOME/.hue_cache/${HIVE_TGZ}"

build_hive() {
  if [ ! -f $HOME/.hue_cache ]; then
    mkdir -p $HOME/.hue_cache
    echo "Downloading $HIVE_URL..."
    wget $HIVE_URL -O $HIVE_CACHE
  fi

  HIVE_DIR=$HUE_ROOT/ext/hive

  mkdir -p $HIVE_DIR
  echo "Unpacking $HIVE_CACHE to $HIVE_DIR"
  tar -C $HIVE_DIR -xzf $HIVE_CACHE
  export HIVE_HOME="$HIVE_DIR/${HIVE_VERSION}"
  export HIVE_CONF_DIR=$HIVE_HOME/conf
}
