# Generated by Django 3.2.20 on 2024-01-09 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('desktop', '0013_alter_document2_is_trashed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('progress', models.CharField(max_length=100)),
                ('task_name', models.CharField(max_length=255)),
                ('parameters', models.JSONField()),
                ('status', models.CharField(max_length=100)),
                ('task_id', models.CharField(max_length=255, unique=True)),
                ('triggered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
