# Generated by Django 3.2.16 on 2023-04-27 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desktop', '0014_sqlquery'),
    ]

    operations = [
        migrations.CreateModel(
            name='SqlQueryParser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('database', models.CharField(default=None, max_length=255)),
                ('table_name', models.CharField(default='', max_length=255)),
                ('column_name', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='SqlQuery',
        ),
    ]
