# Generated by Django 3.2.16 on 2023-05-12 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desktop', '0015_auto_20230427_0301'),
    ]

    operations = [
        migrations.CreateModel(
            name='SqlTopJoins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('database', models.CharField(default=None, max_length=255)),
                ('table_name', models.CharField(default='', max_length=255)),
                ('table_name_1', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
