# Generated by Django 3.2.16 on 2023-04-05 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desktop', '0015_auto_20230330_0018'),
    ]

    operations = [
        migrations.CreateModel(
            name='SqlQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255)),
                ('its_type', models.CharField(default='', max_length=255)),
                ('database', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='SqlLocation',
        ),
    ]
