# Generated by Django 3.2.16 on 2023-05-17 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desktop', '0016_sqltopjoins'),
    ]

    operations = [
        migrations.CreateModel(
            name='SqlParser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('database', models.CharField(default=None, max_length=255)),
                ('table_name', models.CharField(default=None, max_length=255)),
                ('table_name_1', models.CharField(default=None, max_length=255)),
                ('column_name', models.CharField(default=None, max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='SqlQueryParser',
        ),
        migrations.DeleteModel(
            name='SqlTopJoins',
        ),
    ]
