# Generated by Django 3.2.16 on 2023-05-18 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desktop', '0017_auto_20230517_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sqlparser',
            name='column_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='sqlparser',
            name='database',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='sqlparser',
            name='table_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='sqlparser',
            name='table_name_1',
            field=models.CharField(default='', max_length=255),
        ),
    ]
