# Generated by Django 3.2.16 on 2023-06-03 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desktop', '0018_auto_20230518_0007'),
    ]

    operations = [
        migrations.CreateModel(
            name='SqlParserSuggestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('database', models.CharField(default='', max_length=255)),
                ('table_name', models.CharField(default='', max_length=255)),
                ('table_name_1', models.CharField(default='', max_length=255)),
                ('column_name', models.CharField(default='', max_length=255)),
                ('column_name_1', models.CharField(default='', max_length=255)),
                ('join_type', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='SqlParser',
        ),
    ]
