# Generated by Django 3.2.16 on 2023-06-07 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desktop', '0019_auto_20230603_0552'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SqlParserSuggestions',
            new_name='SqlOptimizer',
        ),
    ]
