language: python
cache: pip
matrix:
  include:
  - os: linux
    dist: trusty
    python: '2.6'
  - os: linux
    dist: trusty
    python: '2.7'
  - os: linux
    dist: trusty
    python: '3.2'
  - os: linux
    dist: trusty
    python: '3.3'
  - os: linux
    dist: trusty
    python: '3.4'
  - os: linux
    dist: trusty
    python: '3.5'
  - os: linux
    dist: trusty
    python: '3.6'
  - os: linux
    dist: xenial
    sudo: true
    python: '3.7'
  - os: linux
    dist: trusty
    python: 'nightly'
  - os: linux
    dist: trusty
    python: 'pypy'
  - os: linux
    dist: trusty
    python: 'pypy3'
install:
  - pip install codecov
  - pip install -r requirements.txt -r devel-requirements.txt
  - pip install -e .
script:
  - PYTHONPATH=.:$PYTHONPATH python tests/__main__.py
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then (make -C docs html); fi
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then (make -C docs html); fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.3' ]]; then (make -C docs html); fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.4' ]]; then (make -C docs html); fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.5' ]]; then (make -C docs html); fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then (make -C docs html); fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.7' ]]; then (make -C docs html); fi
  - if [[ $TRAVIS_PYTHON_VERSION == 'nightly' ]]; then (make -C docs html); fi
after_success:
  - PYTHONPATH=.:$PYTHONPATH coverage run --omit=*test* tests/__main__.py
  - codecov
