import sqlStatementsParser, { ParsedSqlStatement } from '../../../../parse/sqlStatementsParser';

export enum GuardrailAlertType {
  UNSAFE_SQL = 'UNSAFE_SQL',
  SEMANTIC_ERROR = 'SEMANTIC_ERROR'
}

const lossAlterWarning = `To prevent accidental loss or altering of data as a result 
of interacting with the AI assistant you need to confirm that you understand what 
this query does before you execute it in the editor.`;

function getFirstKeywordsInUppercase(sqlStatement: string) {
  const parsed: ParsedSqlStatement[] = sqlStatementsParser.parse(sqlStatement);
  console.log(parsed);
  const firstTokens = parsed.map(parsedObj => parsedObj?.firstToken?.toUpperCase());
  return firstTokens.filter(token => token !== undefined);
}

function validateFirstKeyword(keyword: string): { unsafe: boolean; details?: string } {
  let unsafe = true;
  let details;

  switch (keyword) {
    case 'SELECT':
    case 'DESCRIBE':
    case 'SHOW':
      unsafe = false;
      break;
    case 'WITH':
      details = `CTE statements generated by the AI assistant can potentially contain 
      unsafe sub statements. ${lossAlterWarning}`;
      break;
    case 'DELETE':
    case 'TRUNCATE':
    case 'DROP':
      details = `SQL statements starting with ${keyword} are not considered safe to execute since 
      they delete data. To prevent accidental loss of data as a result of interacting with the AI 
      assistant you need to confirm that you understand what this query does before you execute it 
      in the editor.`;
      break;
    case 'INSERT':
    case 'UPDATE':
    case 'REPLACE':
    case 'LOAD':
    case 'ALTER':
    case 'MERGE':
    case 'UPSERT':
      details = `SQL statements starting with ${keyword} are not considered safe to execute since 
      they modify data. To prevent accidental loss of data as a result of interacting with the AI 
      assistant you need to confirm that you understand what this query does before you execute it 
      in the editor.`;
      break;
    default:
      details = `SQL statements starting with ${keyword} are not considered safe to execute. 
      ${lossAlterWarning}`;
      break;
  }
  return { unsafe, details };
}

export function hasUnsafeKeywords(sqlStatement: string): { unsafe: boolean; details?: string } {
  try {
    const firstKeywords = getFirstKeywordsInUppercase(sqlStatement);
    const onlyContainsComment = sqlStatement && firstKeywords.length === 0;

    if (!sqlStatement || onlyContainsComment) return { unsafe: false };

    const validations = firstKeywords.map(validateFirstKeyword);
    const invalidStatement = validations.find(validation => validation.unsafe === true);

    return invalidStatement || { unsafe: false };
  } catch (e) {
    console.error(e);
    return {
      unsafe: true,
      details: `Could not parse the query in order to determine if it is safe to execute. ${lossAlterWarning} `
    };
  }
}

// TODO add types
// TODO USE ENUM TYPE FOR GUARDRAILS ALERT TYPE
export interface GuardrailAlert {
  type: GuardrailAlertType;
  title: string;
  nql: string;
  msg?: string;
  aiMsg?: string;
}

export function withGuardrails(functionToGuard: (...args: any[]) => Promise<any>) {
  return async (...args: any[]) => {
    const result = await functionToGuard(...args);
    const { nql } = args[0];
    const titleUnsafeSqlType = 'Potentially unsafe SQL statement';

    if (result.semanticerror) {
      result.guardrailAlert = {
        type: GuardrailAlertType.SEMANTIC_ERROR,
        title: 'AI failed to understand the input given',
        nql,
        msg: `The AI assistant could not make sense of the request. Try again using different wording.`,
        aiMsg: result.semanticerror
      };
    } else if (result.warning) {
      result.guardrailAlert = {
        type: GuardrailAlertType.UNSAFE_SQL,
        title: titleUnsafeSqlType,
        nql,
        msg: lossAlterWarning,
        aiMsg: result.warning
      };
    } else {
      const { unsafe, details } = hasUnsafeKeywords(result.sql);
      if (unsafe) {
        result.guardrailAlert = {
          type: GuardrailAlertType.UNSAFE_SQL,
          title: titleUnsafeSqlType,
          nql,
          msg: details
        };
      }
    }
    return result;
  };
}
