{
 "title": "Hue - Home",
 "description": "SQL Assistant for Databases & Data Warehouses",
 "tags": [ "hue" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Name Space",
    "query": "label_values(up{namespace=~\"(impala|compute).+\"},namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Time Total",
   "type": "graph",
   "description": "Total user and system CPU time spent in seconds",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_cpu_seconds_total{app=\"huebackend\", namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Resident memory size",
   "type": "graph",
   "description": "Resident memory (Physical memory) size in bytes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{app=\"huebackend\", namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Hue Local Active Users",
   "type": "graph",
   "description": "Hue active users per instance",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hue_local_active_users{app=\"huebackend\", namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Number of Queries",
   "type": "graph",
   "description": "Number of queries last 10 minutes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hue_queries_numbers{app=\"huebackend\", namespace=\"$namespace\"}"
    }
   ]
  }
 ]
}