apiVersion: v1
kind: ConfigMap
metadata:
  name: hue-config
data:
  hue-ini: |
    [impala]
    server_host=hostname.com
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: hue
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hue
    spec:
      containers:
        - name: hue
          image: gethue/hue:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8888
          volumeMounts:
          - name: config-volume
            mountPath: /usr/share/hue/desktop/conf/z-hue.ini
            subPath: hue-ini
      volumes:
        - name: config-volume
          configMap:
            name: hue-config
---
apiVersion: v1
kind: Service
metadata:
  name: hue
spec:
  selector:
    app: hue
  ports:
  - name: hue
    port: 8888
  type: NodePort
