[build-system]
requires = [
    # The minimum setuptools version is specific to the PEP 517 backend,
    # and may be stricter than the version required in `setup.py`
    "setuptools>=40.6.0",
    "wheel",
    # Must be kept in sync with the `setup_requirements` in `setup.py`
    "cffi>=1.12; platform_python_implementation != 'PyPy'",
]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 79
target-version = ["py27"]
