# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-03-11 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useradmin', '0003_auto_20200203_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='hostname',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
