dist: xenial

language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8-dev"

matrix:
  allow_failures:
    - python: "3.8-dev"

install:
  - make bootstrap

script:
  - make test testbed lint
