#
# Autogenerated by Thrift Compiler (0.9.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py:new_style
#

from thrift.Thrift import TType, TMessageType, TException, TApplicationException
from ttypes import *

DEFAULT_QUERY_OPTIONS = {
    0 : "false",
    1 : "0",
    2 : "false",
    3 : "0",
    5 : "0",
    6 : "0",
    7 : "0",
    8 : "0",
    9 : "false",
    10 : "-1",
    11 : "",
    4 : "0",
}
