# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-06 18:55
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oozie', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_node', to='oozie.Node', verbose_name=b''),
        ),
        migrations.AddField(
            model_name='link',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_node', to='oozie.Node'),
        ),
        migrations.AddField(
            model_name='job',
            name='owner',
            field=models.ForeignKey(help_text='Person who can modify the job.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
         migrations.AddField(
            model_name='history',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oozie.Job'),
        ),
    ]
