#!/bin/bash

SRC_DIR=$(dirname $BASH_SOURCE)
CONF_DIR=$SRC_DIR/conf
LOG_DIR=$SRC_DIR/logs
QP_DIR=$SRC_DIR/query-processor/
CP_FILE=$QP_DIR/target/classpath

source $QP_DIR/target/classes/env-version.sh

MAIN_CLASS=com.cloudera.hue.querystore.eventProcessor.EventProcessorApplication
DEBUG_ARGS="-agentlib:jdwp=transport=dt_socket,server=y,address=8000,suspend=y"
YJP_ARGS="-agentpath:/Applications/YourKit-Java-Profiler-2019.1.app/Contents/Resources/bin/mac/libyjpagent.jnilib=disablestacktelemetry,exceptions=disable,listen=all"
JAVA_ARGS="-Dlog4j.configurationFile=$CONF_DIR/hue-query-processor-log4j2.yml -DHADOOP_USER_NAME=hive"

DB=qp_db
DBUSER=qp_user
DBPASS=qp_pass
QP_HOST=cm/cm@amleshkumar-1-o12.amleshkumar-1-o12.root.hwx.site:1521/orcl12c

export HADOOP_CONF=$CONF_DIR
ORACLE_PATH=$(echo /opt/oracle/product/12.2.0/bin/sqlplus)

start() {
  echo "starting Oracle"
#  brew services start mysql
#  PATH="$PATH:$ORACLE_PATH"

#  echo "waiting for mysql ..."
#  sleep 3
#  echo "starting the main script now"
}

stop() {
  echo "stopping Oracle"
#  brew services stop mysql
}

gen_cp() {
  if [ ! -f $CP_FILE ]; then
    echo "Generating classpath"
    mvn -q -nsu -pl query-processor dependency:build-classpath -Dmdep.outputFile=target/classpath -Dmdep.regenerateFile=true
    echo -n ":$QP_DIR/target/hue-query-processor-${HUE_QP_VERSION}.jar" >> $CP_FILE
  fi
}

setup_db() {
  echo "Setting up Oracle qp_db and users ..."
  PATH="$PATH:$ORACLE_PATH"
  
  sqlplus -s $QP_HOST <<< "CREATE USER $DBUSER IDENTIFIED BY $DBPASS;" &&
  sqlplus -s $QP_HOST <<< "GRANT ALL PRIVILEGES TO $DBUSER;" &&

  gen_cp
  echo migrate db ...
  CLASSPATH=$(cat $CP_FILE) java $MAIN_CLASS db migrate $CONF_DIR/hue-query-processor_oracle.json > /dev/null
}

delete_db() {
  echo "Dropping Oracle qp_db and users..."
  PATH="$PATH:$ORACLE_PATH"

  sqlplus -s $QP_HOST <<< "DROP USER $DBUSER CASCADE;"
}

start_java() {
  gen_cp
  echo starting query processor ...
  CLASSPATH=$SRC_DIR/conf/:$(cat $CP_FILE) java $JAVA_ARGS $MAIN_CLASS server $CONF_DIR/hue-query-processor_oracle.json > qp.log 2>&1 &
  echo $! > qp.pid
}

stop_java() {
  echo "Killing java procs ..."
  kill $(cat qp.pid)
}

while (($#)); do
  case $1 in
  start)
    set -e
#    start
    setup_db
    start_java
    ;;
  stop)
    stop_java
    echo "Waiting 5 sec before deleting db"
    sleep 5
    delete_db
    stop
    ;;

  jvstart)
    start_java
    ;;
  jvstop)
    stop_java
    ;;
  msstart)
    start
    ;;
  msstop)
    stop
    ;;
  mssetup)
    setup_db
    ;;
  msreset)
    delete_db
    ;;
  *)
    echo "Usage: $0 <start|stop|jvstart|jvstop|msstart|msstop|mssetup|msreset>"
    exit 1
    ;;
  esac
  shift
done
