dist: xenial
language: python
cache: pip
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7
env:
  - DJANGO=1.11
  - DJANGO=2.0
  - DJANGO=2.1
  - DJANGO=master
matrix:
  exclude:
    - python: 2.7
      env: DJANGO=2.0
    - python: 2.7
      env: DJANGO=2.1
    - python: 2.7
      env: DJANGO=master
    - python: 3.4
      env: DJANGO=2.1
    - python: 3.4
      env: DJANGO=master
install: pip install tox-travis codecov
script: tox
after_success:
  - codecov
deploy:
  provider: pypi
  user: jazzband
  password:
    secure: TCH5tGIggL2wsWce2svMwpEpPiwVOYqq1R3uSBTexszleP0OafNq/wZk2KZEReR5w1Aq68qp5F5Eeh2ZjJTq4f9M4LtTvqQzrmyNP55DYk/uB1rBJm9b4gBgMtAknxdI2g7unkhQEDo4suuPCVofM7rrDughySNpmvlUQYDttHQ=
  server: https://jazzband.co/projects/django-axes/upload
  distributions: sdist bdist_wheel
  skip_existing: true
  on:
    tags: true
    repo: jazzband/django-axes
    python: 3.6
