apiVersion: v1
kind: ConfigMap
metadata:
  name: hue-config
data:
  hue-ini: |
    [desktop]

    [[database]]
    engine={{ .Values.hue.database.engine }}
    host={{ .Values.hue.database.host }}
    port={{ .Values.hue.database.port }}
    user={{ .Values.hue.database.user }}
{{- if .Values.hue.database.password_script }}
    password_script={{ .Values.hue.database.password_script }}
{{- else }}
    password={{ .Values.hue.database.password }}
{{- end }}
    name={{ .Values.hue.database.name }}

    [aws]
    [[aws_accounts]]
    [[[default]]]
    access_key_id={{ .Values.aws.accessKeyId }}
    secret_access_key={{ .Values.aws.secretAccessKey }}
    region={{ .Values.aws.region }}

    [notebook]
    [[interpreters]]
    {{ .Values.hue.interpreters | indent 4 }}
