{{- if .Values.cron.enabled -}}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: email-stats
spec:
  schedule: {{ .Values.cron.emailStats }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: email-stats
            image: {{ .Values.image.registry }}/hue:{{ .Values.image.tag }}
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            args:
            - /bin/bash
            - -c
            - ./build/env/bin/hue send_query_stats
            resources:
              requests:
                cpu: "5m"
            volumeMounts:
            - name: config-volume
              mountPath: /usr/share/hue/desktop/conf/z-hue.ini
              subPath: hue-ini
            - name: config-volume-extra
              mountPath: /usr/share/hue/desktop/conf/zz-hue.ini
              subPath: hue-ini
          restartPolicy: OnFailure
          volumes:
            - name: config-volume
              configMap:
                name: hue-config
            - name: config-volume-extra
              configMap:
                name: hue-config-extra
{{- end -}}
