apiVersion: v1
kind: ConfigMap
metadata:
  name: hue-config
data:
  hue-ini: |
    [desktop]
    [[database]]
    engine={{ .Values.hue.database.engine }}
    host={{ .Values.hue.database.host }}
    port={{ .Values.hue.database.port }}
    user={{ .Values.hue.database.user }}
    password={{ .Values.hue.database.password }}
    name={{ .Values.hue.database.name }}

    [aws]
    [[aws_accounts]]
    [[[default]]]
    access_key_id={{ .Values.aws.awsAccessKeyId }}
    secret_access_key={{ .Values.aws.awsSecretAccessKey }}
    region={{ .Values.aws.awsRegion }}

    [notebook]
    [[interpreters]]
    {{ .Values.hue.interpreters | indent 4 }}
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: hue
spec:
  replicas: {{ .Values.hue.replicas }}
  template:
    metadata:
      labels:
        app: hue
    spec:
      containers:
        - name: hue
          image: {{ .Values.registry }}:{{ .Values.tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: 8888
          volumeMounts:
          - name: config-volume
            mountPath: /usr/share/hue/desktop/conf/z-hue.ini
            subPath: hue-ini
      volumes:
        - name: config-volume
          configMap:
            name: hue-config
---
apiVersion: v1
kind: Service
metadata:
  name: hue
spec:
  selector:
    app: hue
  ports:
  - name: hue
    port: 8888
  type: NodePort
---
{{- if .Values.ingress.create -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hue
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: {{ .Values.domain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: hue
          servicePort: hue
{{- end -}}
