{{- if and .Values.ingress.create (eq .Values.ingress.type "nginx") -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: hue-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: {{ .Values.ingress.domain }}
    http:
      paths:
      - backend:
          serviceName: hue-balancer
          servicePort: 80
        path: /
{{- end -}}
