{{- if .Values.ingress.create -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: traefik-admin-ui
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: traefik.{{ .Values.ingress.domain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: traefik-ingress-service
          servicePort: admin
{{- end -}}
