{{- if and .Values.ingress.create (eq .Values.ingress.type "nginx") -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: hue
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "hue-balancer-ingress"
    nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
spec:
  rules:
  - host: {{ .Values.ingress.domain }}
    http:
      paths:
      - backend:
          serviceName: hue-balancer
          servicePort: 80
        path: /
{{- end -}}
