{{- if .Values.alertrule.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: example
    role: alert-rules
  name: hue
spec:
  groups:
    - name: hue-pod-monitor.alert.rules
      rules:
      - alert: hue_pods_are_down
        expr: sum(up{job="hue",namespace="data-platform-staging"}) < {{ .Values.hue.replicas }} #Based on the replicas mentioned in values.yaml
        for: 30m #Change this based on your SLA
        labels:
          severity: High
        annotations:
          summary: Some Hue pods are down
          impact: Users might not be able to query via Hue Web UI
{{ end }}
