{{- if .Values.alerting.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: example
    role: alert-rules
  name: hue
spec:
  groups:
{{ toYaml .Values.alerting.prometheusRules | indent 4}}
{{ end }}
