{{- if and .Values.hue.database.persist .Values.hue.database.create -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  labels:
    type: local
spec:
  storageClassName: {{ .Values.hue.database.storageName }}
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/postgres-pv
{{- end -}}
