{{- if .Values.hue.database.create -}}
apiVersion: v1
kind: ReplicationController
metadata:
  name: postgres-hue
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres-hue
    spec:
      containers:
        - name: postgres-hue
          image: postgres:9.5
          env:
            - name: POSTGRES_USER
              value: hue
            - name: POSTGRES_PASSWORD
              value: hue
            - name: POSTGRES_DB
              value: hue
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-data
      volumes:
        - name: postgres-data
          {{ if .Values.hue.database.persist }}
          persistentVolumeClaim:
            claimName: postgres-pvc
          {{ else }}
          emptyDir: {}
          {{ end }}
{{- end -}}
