apiVersion: v1
kind: ReplicationController
metadata:
  name: hue
spec:
  replicas: {{ .Values.hue.replicas }}
  template:
    metadata:
      labels:
        app: hue
    spec:
      containers:
        - name: hue
          image: {{ .Values.image.registry }}/hue:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8888
          volumeMounts:
          - name: config-volume
            mountPath: /usr/share/hue/desktop/conf/z-hue.ini
            subPath: hue-ini
          - name: config-volume-extra
            mountPath: /usr/share/hue/desktop/conf/zz-hue.ini
            subPath: hue-ini
          readinessProbe:
            httpGet:
              path: /desktop/debug/is_alive
              port: 8888
            initialDelaySeconds: 3
            periodSeconds: 3
            failureThreshold: 30
      volumes:
        - name: config-volume
          configMap:
            name: hue-config
        - name: config-volume-extra
          configMap:
            name: hue-config-extra
