{{- if .Values.ingress.create -}}
kind: Service
apiVersion: v1
metadata:
  name: traefik-ingress-service
spec:
  selector:
    app: traefik-ingress-lb
  ports:
    - name: web
      port: 80
    - name: admin
      port: 8080
  type: LoadBalancer
  #loadBalancerIp: {{ .Values.loadBalancerIp }}
{{- end -}}
