{{- if .Values.hue.database.create -}}
apiVersion: v1
kind: Service
metadata:
  name: postgres-hue
spec:
  ports:
  - name: pgql
    port: 5432
  type: NodePort
  selector:
    app: postgres-hue
{{- end -}}
