apiVersion: v1
kind: Service
metadata:
  name: hue
spec:
  selector:
    app: hue
  ports:
  - name: hue
    port: 8888
  type: NodePort
---
{{- if .Values.ingress.create -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hue
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: {{ .Values.domain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: hue
          servicePort: hue
{{- end -}}
